;!knitout-2
;;Machine: SWG091N2
;;Gauge: 7
;;Width: 250
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Position: Center
inhook 3
tuck - f50 3
tuck - f49 3
tuck - f48 3
tuck - f47 3
releasehook 3
knit + f47 3
knit + f48 3
knit + f49 3
knit + f50 3
knit - f50 3
knit - f49 3
knit - f48 3
knit - f47 3
knit + f47 3
knit + f48 3
knit + f49 3
knit + f50 3
knit - f50 3
knit - f49 3
knit - f48 3
knit - f47 3
outhook 3
