;!knitout-2
;;Machine: SWG091N2
;;Gauge: 7
;;Width: 250
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Position: Center
inhook 1
tuck - f50 1
tuck - f49 1
tuck - f48 1
tuck - f47 1
releasehook 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
outhook 1
